export const actionTypes = {
  GET_EXAMPLE: 'GET_EXAMPLE',
  POST_EXAMPLE: 'POST_EXAMPLE',
  UPDATE_EXAMPLE: 'UPDATE_EXAMPLE',
  SET_LOADING: 'SET_LOADING',
  SET_FILTER_MENU: 'SET_FILTER_MENU',
  SET_FILTER_SORT: 'SET_FILTER_SORT',
  SET_SEARCH_TEXT: 'SET_SEARCH_TEXT'
}
