export const actionTypes = {
  GET_EXAMPLE: 'GET_EXAMPLE',
  GET_REFINEMENTS: 'GET_REFINEMENTS',
  POST_EXAMPLE: 'POST_EXAMPLE',
  POST_REFINEMENTS: 'POST_REFINEMENTS',
  UPDATE_EXAMPLE: 'UPDATE_EXAMPLE',
  UPDATE_REFINEMENTS: 'UPDATE_REFINEMENTS',
  SET_LOADING: 'SET_LOADING',
  SET_FILTER_MENU: 'SET_FILTER_MENU',
  SET_FILTER_SORT: 'SET_FILTER_SORT',
  SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
  SET_SELECTION: 'SET_SELECTION',
  SET_INIT_SELECTIONS: 'SET_INIT_SELECTION',
  SET_FILTER: 'SET_FILTER'
}
